### ISSUE TITLE
Add preemption by Job priority

### ISSUE THREAD

**Issue by k82cn** [kubernetes-retired/kube-batch#261]
According to the requirement of https://github.com/kubernetes/kubernetes/issues/65746 , it's better to also provide Job priority. To work together with DRF and other policy/algorithm, it's also better to make preemption level configurable, e.g. Job priority can overwrite DRF when doing preemption .

**Comment by k82cn** [comment]
Removed this from 0.1 release as we need admission for SchedulingSpec's priority. And I think we can not catch 0.1 release.

**Comment by k82cn** [comment]
dependent on https://github.com/kubernetes-sigs/kube-batch/issues/484 ; the job priority plugin should be a higher tier plugin than others if necessary :)

**Comment by Rajadeepan** [comment]
Along with adding priority classes one possible solution for handle this issue is.......
 - Addition of prempt function in priority plugin which selects victims only if the job of premptor task has higher priority than job of the premptee task.
 But this might fail if this premptee task voilates the gang scheduling minAvailable condition for premption

As per the requirement https://github.com/kubernetes/kubernetes/issues/65746
- Annotation can be added in jobspec  "PriorityPreempt":"true" which will not check for any other plugin premption logic but force the the task of the job (preemptee) which  does not has annotation "PriorityPreempt" to prempt

If the annotation "PriorityPreempt" of the job is not present then run through all the plugins premption logic as usual....
@k82cn  Please suggest if this solution makes sense
