### ISSUE TITLE
Added benchmark of kube-batch

### ISSUE THREAD

**Issue by k82cn** [kubernetes-retired/kube-batch#427]
**DESCRIPTION**: -- symptom of the problem a customer would see

After enabled pod affinity/anti-affinity at https://github.com/kubernetes-sigs/kube-batch/pull/418 , we need to know the impact to the kube-batch performance.

**Comment by Jeffwan** [comment]
1. I think this one depends on #487? Once kube-batch exposes metric, it would be easy to check benchmark result. 
2. Do we also want to add benchmark utilities like https://github.com/kubernetes/perf-tests?

**Comment by k82cn** [comment]
both are necessary :) 

metrics is helpful for product, perf is helpful for test, debug. I think we can do metrics firstly.

**Comment by thandayuthapani** [comment]
For benchmark of kube-batch using scheduler-perf a WIP PR has been raised https://github.com/kubernetes-sigs/kube-batch/pull/597, but there are problems in scheduler-perf test integration suite, since they bring up API Server without CRD Support, but kube-batch depends on CRDs like PodGroup, We are trying to add CRD Capability to the API Server, which is being brought up by scheduler-perf integration test suite.  This is where we are working on now to bring CRD capability to that API Server, and that is our blocking point now.
