### ISSUE TITLE
Propose not to delete all pods after the job finished

### ISSUE THREAD

**Issue by hzxuzhonghu** [kubernetes-retired/kube-batch#797]
After I run a `batch.volcano.sh/Job`, i want to look at the logs of the task. But i find the pods are all deleted. 
 I think it is common use case to check the logs., so i would keep all the job related resources. until user explicitly want to delete.

**Comment by SrinivasChilveri** [comment]
I think any how user need not required to delete each pod explicitly ,as he deletes volcano job automatically the pods will be deleted ,so I think its always better to give more flexibility to user, to delete his own created jobs & related resources like pods,pvcs,services etc. even if we see currently we are delete-ting the  service, pvc etc during the  batch.volcano.sh/Job deletion by using the OwnerReferences as shown below.

Its better to follow the same for pods instead of explicit deleting on completed

In createJobIOIfNotExist func 
pvc := &v1.PersistentVolumeClaim{
					ObjectMeta: metav1.ObjectMeta{
						Namespace: job.Namespace,
						Name:      outputPVC,
						OwnerReferences: []metav1.OwnerReference{
							*metav1.NewControllerRef(job, helpers.JobKind),
						},
					},
					Spec: *job.Spec.Output.VolumeClaim,
				}
