### ISSUE TITLE
Support both version of PodGroup

### ISSUE THREAD

**Issue by k82cn** [kubernetes-retired/kube-batch#866]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

We also need to support `PodGroup.scheduling.sigs.dev/v1alpha2` in https://github.com/kubernetes-sigs/kube-batch/tree/master/pkg/apis/scheduling/v1alpha2 .

**Comment by k82cn** [comment]
/assign @asifdxtreme 

BTW, we also need to include Queue in v1alpha2.

**Comment by thandayuthapani** [comment]
@k82cn Do we need to have two different packages and build two different binaries for different versions.  Or we have to support both the version in a single package and have it in single binary(In this approach, we need to have two objects of podGroup of different versions to be maintained in JobInfo struct)?

**Comment by k82cn** [comment]
just one binary; introduce a new internal object PodGroupInfo, convert different version of podGroup into internal object.

**Comment by thandayuthapani** [comment]
@k82cn Even when we convert those types to internal object, we are facing problems when event is to be generated to that object, since it will not be runtime object.  
Even if we implement deep copy function to that internal object to be accepted as runtime object(needs deep copy function implemented on those structs), then API server will not be able to find that type since that is internal object.
