### ISSUE TITLE
[Question] How to delete Podgroup and job if unschedulable

### ISSUE THREAD

**Issue by qw2208** [kubernetes-retired/kube-batch#903]
> /kind feature

**What happened**:
If the podgroup and jobs are not schedulable, the jobs and podgroup will be in pending status and will not delete the resources.

Is there any config for this if in pending status, then automatically delete the podgroup and job instead of retriggering?

**Comment by xial-thu** [comment]
see https://github.com/kubernetes-sigs/kube-batch/pull/847 and https://github.com/kubernetes-sigs/kube-batch/pull/821. the pr's have been discussed in detail and maybe you can hack kube-batch as a temporary solution.

BTW, does anyone knows the impact of multiple schedulers within one cluster due to data inconsistency? I've googled a lot but no authoritative answer, sad.

**Comment by qw2208** [comment]
Yep I've raised this issue #922.
