### ISSUE TITLE
Question: Gang scheduling not working while cpu usage is close to the limitations and pods could still be scheduled

### ISSUE THREAD

**Issue by qw2208** [kubernetes-retired/kube-batch#938]
Hi,

/kind bug

I've got the problem related to gang scheduling of kube-batch. When cpu request are close to the node limits, the gang scheduling `seems a failure`. One of the pods is not started and reported error by Kubelet while other pods are running. The pods running on the drought node were scheduled hours ago.

See my following experiment as an example. I've created a podgroup and a batch of pods with the following configs:
![image](https://user-images.githubusercontent.com/24438413/80455307-14602d80-895e-11ea-8a71-b16f605377a8.png)
What I expect is that all the pods are pending and Failed to be scheduled. However, I got all the pods got scheduled but one of them gave the error of outofcpu:
![image](https://user-images.githubusercontent.com/24438413/80449426-ba596b00-8951-11ea-8933-f7416a666df3.png)
The node status is as following.
![image](https://user-images.githubusercontent.com/24438413/80449520-f096ea80-8951-11ea-9a3d-ece03a877d61.png)

Another observation is: Seems if the gap is large, kube-batch pends all the pods, which meets the expectation

**Comment by qw2208** [comment]
Another observation is: Seems if the gap is large, kube-batch pends all the pods.

**Comment by Cherishty** [comment]
Hi Team,

I meet the same issue as well, and my scenario is:

I have a pod-group that contains 4 pods, all of which are `1cpu, 1GB memory`. Although my cluster only has 3.6cpu, these pods are scheduled to the nodes successfully, then the kubelet process on one node print the error message like above, and one pod fails to create.

However, if I apply for 4 * `1.5cpu, 1GB`, gang-scheduling will work and all pods are rejected to schedule

**Reminder**: in my scenario, I reserve 0.5cpu per node for system-use when init the k8s cluster, which means my VM has 8cpu, but only 7.5cpu is `allocatable`(seems @qw2208 also has this configuration). Is this the root cause?
